const mockFollowers = [
  {
    login: 'bradl3yC',
    id: 6165421,
    node_id: 'MDQ6VXNlcjYxNjU0MjE=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6165421?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/bradl3yC',
    html_url: 'https://github.com/bradl3yC',
    followers_url: 'https://api.github.com/users/bradl3yC/followers',
    following_url:
      'https://api.github.com/users/bradl3yC/following{/other_user}',
    gists_url: 'https://api.github.com/users/bradl3yC/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/bradl3yC/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/bradl3yC/subscriptions',
    organizations_url: 'https://api.github.com/users/bradl3yC/orgs',
    repos_url: 'https://api.github.com/users/bradl3yC/repos',
    events_url: 'https://api.github.com/users/bradl3yC/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/bradl3yC/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'dean9090',
    id: 29636023,
    node_id: 'MDQ6VXNlcjI5NjM2MDIz',
    avatar_url: 'https://avatars.githubusercontent.com/u/29636023?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/dean9090',
    html_url: 'https://github.com/dean9090',
    followers_url: 'https://api.github.com/users/dean9090/followers',
    following_url:
      'https://api.github.com/users/dean9090/following{/other_user}',
    gists_url: 'https://api.github.com/users/dean9090/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/dean9090/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/dean9090/subscriptions',
    organizations_url: 'https://api.github.com/users/dean9090/orgs',
    repos_url: 'https://api.github.com/users/dean9090/repos',
    events_url: 'https://api.github.com/users/dean9090/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/dean9090/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mandyleigh314',
    id: 21283730,
    node_id: 'MDQ6VXNlcjIxMjgzNzMw',
    avatar_url: 'https://avatars.githubusercontent.com/u/21283730?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mandyleigh314',
    html_url: 'https://github.com/mandyleigh314',
    followers_url: 'https://api.github.com/users/mandyleigh314/followers',
    following_url:
      'https://api.github.com/users/mandyleigh314/following{/other_user}',
    gists_url: 'https://api.github.com/users/mandyleigh314/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/mandyleigh314/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/mandyleigh314/subscriptions',
    organizations_url: 'https://api.github.com/users/mandyleigh314/orgs',
    repos_url: 'https://api.github.com/users/mandyleigh314/repos',
    events_url: 'https://api.github.com/users/mandyleigh314/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mandyleigh314/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'shaunhailey',
    id: 29711358,
    node_id: 'MDQ6VXNlcjI5NzExMzU4',
    avatar_url: 'https://avatars.githubusercontent.com/u/29711358?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/shaunhailey',
    html_url: 'https://github.com/shaunhailey',
    followers_url: 'https://api.github.com/users/shaunhailey/followers',
    following_url:
      'https://api.github.com/users/shaunhailey/following{/other_user}',
    gists_url: 'https://api.github.com/users/shaunhailey/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/shaunhailey/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/shaunhailey/subscriptions',
    organizations_url: 'https://api.github.com/users/shaunhailey/orgs',
    repos_url: 'https://api.github.com/users/shaunhailey/repos',
    events_url: 'https://api.github.com/users/shaunhailey/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/shaunhailey/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'OptionSelect',
    id: 29178824,
    node_id: 'MDQ6VXNlcjI5MTc4ODI0',
    avatar_url: 'https://avatars.githubusercontent.com/u/29178824?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/OptionSelect',
    html_url: 'https://github.com/OptionSelect',
    followers_url: 'https://api.github.com/users/OptionSelect/followers',
    following_url:
      'https://api.github.com/users/OptionSelect/following{/other_user}',
    gists_url: 'https://api.github.com/users/OptionSelect/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/OptionSelect/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/OptionSelect/subscriptions',
    organizations_url: 'https://api.github.com/users/OptionSelect/orgs',
    repos_url: 'https://api.github.com/users/OptionSelect/repos',
    events_url: 'https://api.github.com/users/OptionSelect/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/OptionSelect/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'BreeJax',
    id: 29646854,
    node_id: 'MDQ6VXNlcjI5NjQ2ODU0',
    avatar_url: 'https://avatars.githubusercontent.com/u/29646854?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/BreeJax',
    html_url: 'https://github.com/BreeJax',
    followers_url: 'https://api.github.com/users/BreeJax/followers',
    following_url:
      'https://api.github.com/users/BreeJax/following{/other_user}',
    gists_url: 'https://api.github.com/users/BreeJax/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/BreeJax/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/BreeJax/subscriptions',
    organizations_url: 'https://api.github.com/users/BreeJax/orgs',
    repos_url: 'https://api.github.com/users/BreeJax/repos',
    events_url: 'https://api.github.com/users/BreeJax/events{/privacy}',
    received_events_url: 'https://api.github.com/users/BreeJax/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'jdiboll13',
    id: 29615679,
    node_id: 'MDQ6VXNlcjI5NjE1Njc5',
    avatar_url: 'https://avatars.githubusercontent.com/u/29615679?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jdiboll13',
    html_url: 'https://github.com/jdiboll13',
    followers_url: 'https://api.github.com/users/jdiboll13/followers',
    following_url:
      'https://api.github.com/users/jdiboll13/following{/other_user}',
    gists_url: 'https://api.github.com/users/jdiboll13/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jdiboll13/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jdiboll13/subscriptions',
    organizations_url: 'https://api.github.com/users/jdiboll13/orgs',
    repos_url: 'https://api.github.com/users/jdiboll13/repos',
    events_url: 'https://api.github.com/users/jdiboll13/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jdiboll13/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'JaviJasso',
    id: 17601249,
    node_id: 'MDQ6VXNlcjE3NjAxMjQ5',
    avatar_url: 'https://avatars.githubusercontent.com/u/17601249?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/JaviJasso',
    html_url: 'https://github.com/JaviJasso',
    followers_url: 'https://api.github.com/users/JaviJasso/followers',
    following_url:
      'https://api.github.com/users/JaviJasso/following{/other_user}',
    gists_url: 'https://api.github.com/users/JaviJasso/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/JaviJasso/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/JaviJasso/subscriptions',
    organizations_url: 'https://api.github.com/users/JaviJasso/orgs',
    repos_url: 'https://api.github.com/users/JaviJasso/repos',
    events_url: 'https://api.github.com/users/JaviJasso/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/JaviJasso/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'sanlouise',
    id: 14869324,
    node_id: 'MDQ6VXNlcjE0ODY5MzI0',
    avatar_url: 'https://avatars.githubusercontent.com/u/14869324?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/sanlouise',
    html_url: 'https://github.com/sanlouise',
    followers_url: 'https://api.github.com/users/sanlouise/followers',
    following_url:
      'https://api.github.com/users/sanlouise/following{/other_user}',
    gists_url: 'https://api.github.com/users/sanlouise/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/sanlouise/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/sanlouise/subscriptions',
    organizations_url: 'https://api.github.com/users/sanlouise/orgs',
    repos_url: 'https://api.github.com/users/sanlouise/repos',
    events_url: 'https://api.github.com/users/sanlouise/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/sanlouise/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'ct-rogers',
    id: 26282882,
    node_id: 'MDQ6VXNlcjI2MjgyODgy',
    avatar_url: 'https://avatars.githubusercontent.com/u/26282882?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ct-rogers',
    html_url: 'https://github.com/ct-rogers',
    followers_url: 'https://api.github.com/users/ct-rogers/followers',
    following_url:
      'https://api.github.com/users/ct-rogers/following{/other_user}',
    gists_url: 'https://api.github.com/users/ct-rogers/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/ct-rogers/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ct-rogers/subscriptions',
    organizations_url: 'https://api.github.com/users/ct-rogers/orgs',
    repos_url: 'https://api.github.com/users/ct-rogers/repos',
    events_url: 'https://api.github.com/users/ct-rogers/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/ct-rogers/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'jakelafond',
    id: 8374242,
    node_id: 'MDQ6VXNlcjgzNzQyNDI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/8374242?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jakelafond',
    html_url: 'https://github.com/jakelafond',
    followers_url: 'https://api.github.com/users/jakelafond/followers',
    following_url:
      'https://api.github.com/users/jakelafond/following{/other_user}',
    gists_url: 'https://api.github.com/users/jakelafond/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jakelafond/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jakelafond/subscriptions',
    organizations_url: 'https://api.github.com/users/jakelafond/orgs',
    repos_url: 'https://api.github.com/users/jakelafond/repos',
    events_url: 'https://api.github.com/users/jakelafond/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jakelafond/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'MiguelBrito1086',
    id: 27711630,
    node_id: 'MDQ6VXNlcjI3NzExNjMw',
    avatar_url: 'https://avatars.githubusercontent.com/u/27711630?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/MiguelBrito1086',
    html_url: 'https://github.com/MiguelBrito1086',
    followers_url: 'https://api.github.com/users/MiguelBrito1086/followers',
    following_url:
      'https://api.github.com/users/MiguelBrito1086/following{/other_user}',
    gists_url: 'https://api.github.com/users/MiguelBrito1086/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/MiguelBrito1086/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/MiguelBrito1086/subscriptions',
    organizations_url: 'https://api.github.com/users/MiguelBrito1086/orgs',
    repos_url: 'https://api.github.com/users/MiguelBrito1086/repos',
    events_url: 'https://api.github.com/users/MiguelBrito1086/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/MiguelBrito1086/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'garrettbsettles',
    id: 23278639,
    node_id: 'MDQ6VXNlcjIzMjc4NjM5',
    avatar_url: 'https://avatars.githubusercontent.com/u/23278639?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/garrettbsettles',
    html_url: 'https://github.com/garrettbsettles',
    followers_url: 'https://api.github.com/users/garrettbsettles/followers',
    following_url:
      'https://api.github.com/users/garrettbsettles/following{/other_user}',
    gists_url: 'https://api.github.com/users/garrettbsettles/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/garrettbsettles/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/garrettbsettles/subscriptions',
    organizations_url: 'https://api.github.com/users/garrettbsettles/orgs',
    repos_url: 'https://api.github.com/users/garrettbsettles/repos',
    events_url: 'https://api.github.com/users/garrettbsettles/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/garrettbsettles/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Grego22',
    id: 29668537,
    node_id: 'MDQ6VXNlcjI5NjY4NTM3',
    avatar_url: 'https://avatars.githubusercontent.com/u/29668537?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Grego22',
    html_url: 'https://github.com/Grego22',
    followers_url: 'https://api.github.com/users/Grego22/followers',
    following_url:
      'https://api.github.com/users/Grego22/following{/other_user}',
    gists_url: 'https://api.github.com/users/Grego22/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Grego22/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Grego22/subscriptions',
    organizations_url: 'https://api.github.com/users/Grego22/orgs',
    repos_url: 'https://api.github.com/users/Grego22/repos',
    events_url: 'https://api.github.com/users/Grego22/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Grego22/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'cclarks',
    id: 29711091,
    node_id: 'MDQ6VXNlcjI5NzExMDkx',
    avatar_url: 'https://avatars.githubusercontent.com/u/29711091?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/cclarks',
    html_url: 'https://github.com/cclarks',
    followers_url: 'https://api.github.com/users/cclarks/followers',
    following_url:
      'https://api.github.com/users/cclarks/following{/other_user}',
    gists_url: 'https://api.github.com/users/cclarks/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/cclarks/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/cclarks/subscriptions',
    organizations_url: 'https://api.github.com/users/cclarks/orgs',
    repos_url: 'https://api.github.com/users/cclarks/repos',
    events_url: 'https://api.github.com/users/cclarks/events{/privacy}',
    received_events_url: 'https://api.github.com/users/cclarks/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'LinnJS',
    id: 23741323,
    node_id: 'MDQ6VXNlcjIzNzQxMzIz',
    avatar_url: 'https://avatars.githubusercontent.com/u/23741323?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/LinnJS',
    html_url: 'https://github.com/LinnJS',
    followers_url: 'https://api.github.com/users/LinnJS/followers',
    following_url: 'https://api.github.com/users/LinnJS/following{/other_user}',
    gists_url: 'https://api.github.com/users/LinnJS/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/LinnJS/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/LinnJS/subscriptions',
    organizations_url: 'https://api.github.com/users/LinnJS/orgs',
    repos_url: 'https://api.github.com/users/LinnJS/repos',
    events_url: 'https://api.github.com/users/LinnJS/events{/privacy}',
    received_events_url: 'https://api.github.com/users/LinnJS/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mlta',
    id: 29711296,
    node_id: 'MDQ6VXNlcjI5NzExMjk2',
    avatar_url: 'https://avatars.githubusercontent.com/u/29711296?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mlta',
    html_url: 'https://github.com/mlta',
    followers_url: 'https://api.github.com/users/mlta/followers',
    following_url: 'https://api.github.com/users/mlta/following{/other_user}',
    gists_url: 'https://api.github.com/users/mlta/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mlta/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mlta/subscriptions',
    organizations_url: 'https://api.github.com/users/mlta/orgs',
    repos_url: 'https://api.github.com/users/mlta/repos',
    events_url: 'https://api.github.com/users/mlta/events{/privacy}',
    received_events_url: 'https://api.github.com/users/mlta/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'crystalrmcgowan',
    id: 27657944,
    node_id: 'MDQ6VXNlcjI3NjU3OTQ0',
    avatar_url: 'https://avatars.githubusercontent.com/u/27657944?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/crystalrmcgowan',
    html_url: 'https://github.com/crystalrmcgowan',
    followers_url: 'https://api.github.com/users/crystalrmcgowan/followers',
    following_url:
      'https://api.github.com/users/crystalrmcgowan/following{/other_user}',
    gists_url: 'https://api.github.com/users/crystalrmcgowan/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/crystalrmcgowan/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/crystalrmcgowan/subscriptions',
    organizations_url: 'https://api.github.com/users/crystalrmcgowan/orgs',
    repos_url: 'https://api.github.com/users/crystalrmcgowan/repos',
    events_url: 'https://api.github.com/users/crystalrmcgowan/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/crystalrmcgowan/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Yana727',
    id: 23454977,
    node_id: 'MDQ6VXNlcjIzNDU0OTc3',
    avatar_url: 'https://avatars.githubusercontent.com/u/23454977?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Yana727',
    html_url: 'https://github.com/Yana727',
    followers_url: 'https://api.github.com/users/Yana727/followers',
    following_url:
      'https://api.github.com/users/Yana727/following{/other_user}',
    gists_url: 'https://api.github.com/users/Yana727/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Yana727/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Yana727/subscriptions',
    organizations_url: 'https://api.github.com/users/Yana727/orgs',
    repos_url: 'https://api.github.com/users/Yana727/repos',
    events_url: 'https://api.github.com/users/Yana727/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Yana727/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Groude',
    id: 5012405,
    node_id: 'MDQ6VXNlcjUwMTI0MDU=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5012405?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Groude',
    html_url: 'https://github.com/Groude',
    followers_url: 'https://api.github.com/users/Groude/followers',
    following_url: 'https://api.github.com/users/Groude/following{/other_user}',
    gists_url: 'https://api.github.com/users/Groude/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Groude/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Groude/subscriptions',
    organizations_url: 'https://api.github.com/users/Groude/orgs',
    repos_url: 'https://api.github.com/users/Groude/repos',
    events_url: 'https://api.github.com/users/Groude/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Groude/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'RobbyBourne1',
    id: 27830572,
    node_id: 'MDQ6VXNlcjI3ODMwNTcy',
    avatar_url: 'https://avatars.githubusercontent.com/u/27830572?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/RobbyBourne1',
    html_url: 'https://github.com/RobbyBourne1',
    followers_url: 'https://api.github.com/users/RobbyBourne1/followers',
    following_url:
      'https://api.github.com/users/RobbyBourne1/following{/other_user}',
    gists_url: 'https://api.github.com/users/RobbyBourne1/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/RobbyBourne1/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/RobbyBourne1/subscriptions',
    organizations_url: 'https://api.github.com/users/RobbyBourne1/orgs',
    repos_url: 'https://api.github.com/users/RobbyBourne1/repos',
    events_url: 'https://api.github.com/users/RobbyBourne1/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/RobbyBourne1/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'RoadSigns',
    id: 5822139,
    node_id: 'MDQ6VXNlcjU4MjIxMzk=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5822139?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/RoadSigns',
    html_url: 'https://github.com/RoadSigns',
    followers_url: 'https://api.github.com/users/RoadSigns/followers',
    following_url:
      'https://api.github.com/users/RoadSigns/following{/other_user}',
    gists_url: 'https://api.github.com/users/RoadSigns/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/RoadSigns/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/RoadSigns/subscriptions',
    organizations_url: 'https://api.github.com/users/RoadSigns/orgs',
    repos_url: 'https://api.github.com/users/RoadSigns/repos',
    events_url: 'https://api.github.com/users/RoadSigns/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/RoadSigns/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'DanThePutzer',
    id: 25454503,
    node_id: 'MDQ6VXNlcjI1NDU0NTAz',
    avatar_url: 'https://avatars.githubusercontent.com/u/25454503?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DanThePutzer',
    html_url: 'https://github.com/DanThePutzer',
    followers_url: 'https://api.github.com/users/DanThePutzer/followers',
    following_url:
      'https://api.github.com/users/DanThePutzer/following{/other_user}',
    gists_url: 'https://api.github.com/users/DanThePutzer/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DanThePutzer/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/DanThePutzer/subscriptions',
    organizations_url: 'https://api.github.com/users/DanThePutzer/orgs',
    repos_url: 'https://api.github.com/users/DanThePutzer/repos',
    events_url: 'https://api.github.com/users/DanThePutzer/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DanThePutzer/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'HEYITSJ0HNNY',
    id: 29168080,
    node_id: 'MDQ6VXNlcjI5MTY4MDgw',
    avatar_url: 'https://avatars.githubusercontent.com/u/29168080?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/HEYITSJ0HNNY',
    html_url: 'https://github.com/HEYITSJ0HNNY',
    followers_url: 'https://api.github.com/users/HEYITSJ0HNNY/followers',
    following_url:
      'https://api.github.com/users/HEYITSJ0HNNY/following{/other_user}',
    gists_url: 'https://api.github.com/users/HEYITSJ0HNNY/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/HEYITSJ0HNNY/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/HEYITSJ0HNNY/subscriptions',
    organizations_url: 'https://api.github.com/users/HEYITSJ0HNNY/orgs',
    repos_url: 'https://api.github.com/users/HEYITSJ0HNNY/repos',
    events_url: 'https://api.github.com/users/HEYITSJ0HNNY/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/HEYITSJ0HNNY/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Tallestthomas',
    id: 10948149,
    node_id: 'MDQ6VXNlcjEwOTQ4MTQ5',
    avatar_url: 'https://avatars.githubusercontent.com/u/10948149?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Tallestthomas',
    html_url: 'https://github.com/Tallestthomas',
    followers_url: 'https://api.github.com/users/Tallestthomas/followers',
    following_url:
      'https://api.github.com/users/Tallestthomas/following{/other_user}',
    gists_url: 'https://api.github.com/users/Tallestthomas/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Tallestthomas/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/Tallestthomas/subscriptions',
    organizations_url: 'https://api.github.com/users/Tallestthomas/orgs',
    repos_url: 'https://api.github.com/users/Tallestthomas/repos',
    events_url: 'https://api.github.com/users/Tallestthomas/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Tallestthomas/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Bradzerafa',
    id: 29835518,
    node_id: 'MDQ6VXNlcjI5ODM1NTE4',
    avatar_url: 'https://avatars.githubusercontent.com/u/29835518?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Bradzerafa',
    html_url: 'https://github.com/Bradzerafa',
    followers_url: 'https://api.github.com/users/Bradzerafa/followers',
    following_url:
      'https://api.github.com/users/Bradzerafa/following{/other_user}',
    gists_url: 'https://api.github.com/users/Bradzerafa/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Bradzerafa/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Bradzerafa/subscriptions',
    organizations_url: 'https://api.github.com/users/Bradzerafa/orgs',
    repos_url: 'https://api.github.com/users/Bradzerafa/repos',
    events_url: 'https://api.github.com/users/Bradzerafa/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Bradzerafa/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'jvaleskasilva',
    id: 12084638,
    node_id: 'MDQ6VXNlcjEyMDg0NjM4',
    avatar_url: 'https://avatars.githubusercontent.com/u/12084638?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jvaleskasilva',
    html_url: 'https://github.com/jvaleskasilva',
    followers_url: 'https://api.github.com/users/jvaleskasilva/followers',
    following_url:
      'https://api.github.com/users/jvaleskasilva/following{/other_user}',
    gists_url: 'https://api.github.com/users/jvaleskasilva/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jvaleskasilva/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/jvaleskasilva/subscriptions',
    organizations_url: 'https://api.github.com/users/jvaleskasilva/orgs',
    repos_url: 'https://api.github.com/users/jvaleskasilva/repos',
    events_url: 'https://api.github.com/users/jvaleskasilva/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jvaleskasilva/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'markbojesen',
    id: 16540070,
    node_id: 'MDQ6VXNlcjE2NTQwMDcw',
    avatar_url: 'https://avatars.githubusercontent.com/u/16540070?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/markbojesen',
    html_url: 'https://github.com/markbojesen',
    followers_url: 'https://api.github.com/users/markbojesen/followers',
    following_url:
      'https://api.github.com/users/markbojesen/following{/other_user}',
    gists_url: 'https://api.github.com/users/markbojesen/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/markbojesen/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/markbojesen/subscriptions',
    organizations_url: 'https://api.github.com/users/markbojesen/orgs',
    repos_url: 'https://api.github.com/users/markbojesen/repos',
    events_url: 'https://api.github.com/users/markbojesen/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/markbojesen/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'travismontoya',
    id: 6798640,
    node_id: 'MDQ6VXNlcjY3OTg2NDA=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6798640?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/travismontoya',
    html_url: 'https://github.com/travismontoya',
    followers_url: 'https://api.github.com/users/travismontoya/followers',
    following_url:
      'https://api.github.com/users/travismontoya/following{/other_user}',
    gists_url: 'https://api.github.com/users/travismontoya/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/travismontoya/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/travismontoya/subscriptions',
    organizations_url: 'https://api.github.com/users/travismontoya/orgs',
    repos_url: 'https://api.github.com/users/travismontoya/repos',
    events_url: 'https://api.github.com/users/travismontoya/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/travismontoya/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'oixchi',
    id: 24590137,
    node_id: 'MDQ6VXNlcjI0NTkwMTM3',
    avatar_url: 'https://avatars.githubusercontent.com/u/24590137?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/oixchi',
    html_url: 'https://github.com/oixchi',
    followers_url: 'https://api.github.com/users/oixchi/followers',
    following_url: 'https://api.github.com/users/oixchi/following{/other_user}',
    gists_url: 'https://api.github.com/users/oixchi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/oixchi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/oixchi/subscriptions',
    organizations_url: 'https://api.github.com/users/oixchi/orgs',
    repos_url: 'https://api.github.com/users/oixchi/repos',
    events_url: 'https://api.github.com/users/oixchi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/oixchi/received_events',
    type: 'User',
    site_admin: false,
  },
];

export default mockFollowers;
